const products = [
  { id: "1", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "2", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "3", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "4", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "5", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "6", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "7", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "8", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "9", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "10", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },

  { id: "11", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "12", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "13", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "14", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "15", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "16", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "17", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "18", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "19", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "20", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },

  { id: "21", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "22", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "23", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "24", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "25", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "26", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "27", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "28", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "29", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "30", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },

  { id: "31", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "32", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "33", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "34", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "35", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "36", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "37", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "38", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "39", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
  { id: "40", code: "", name: "", description: "", price: "", category: "", stock: "", img1: "", img2: "", img3: "", img4: "" },
]